### ISSUE TITLE
hide the remaining unsafe part under the macro

### ISSUE THREAD

**Issue by Aalivexy** [ultimaweapon/zfi#1]
Maybe we can hide the remaining unsafe part under the macro, use the macro to generate the real efi_main function, and then call main after processing the unsafe part like _start in C?

**Comment by ultimaweapon** [comment]
We can provide this as an alternative to raw `efi_main`. We need to keep the ability to use raw `efi_main` for the users who don't want this magic.

**Comment by Aalivexy** [comment]
> We can provide this as an alternative to raw `efi_main`. We need to keep the ability to use raw `efi_main` for the users who don't want this magic.

Of course, you are right.  (But with my limited knowledge, it seems that there is no way to restrict users to use raw efi_main directly)

**Comment by ultimaweapon** [comment]
I'll implement this once I finished with the test supports crate. I'm happy to accept a PR for this if you would like to do it.

**Comment by Aalivexy** [comment]
I tried to implement it, probably like this: https://github.com/ultimicro/zfi/compare/main...Aalivexy:zfi:entry_macro
But I have some problems:
  - First, how should this macro be named? I simply named it `zfi::entry!(main);`
  - Secondly, since the `Box` in `alloc` needs to be used in the macro, I can only directly put `extern crate alloc;` into the macro. Of course, there may be no harm in this, after all, it is necessary to introduce `alloc`
  - I limited the signature of the `main` function so that only the main function that conforms to the signature can be compiled
  - I included `global_allocator` inside the macro, for most users they won't change it, so I think it's better to import directly

The simplest hello world after adding the macro should look like this:
```
#![no_std]
#![no_main]

use zfi::{pause, println, Image, Status, SystemTable};

zfi::entry!(main);
fn main(_image: &'static Image, _st: &'static SystemTable) -> Status {
     println!("Hello, world!");
     pause();
     Status::SUCCESS
}

#[panic_handler]
fn panic_handler(info: &core::panic::PanicInfo) -> ! {
     zfi::eprintln!("{info}");
     loop {}
}
```

This is my first time writing a macro, so please forgive me if there are any problems.
